import assert from "node:assert/strict";
import { access, readFile } from "node:fs/promises";
import test from "node:test";

test("PWA manifest is installable and icons exist", async () => {
  const manifest = JSON.parse(await readFile("public/manifest.webmanifest", "utf8"));

  assert.equal(manifest.name, "Renal Dose Calculator");
  assert.equal(manifest.display, "standalone");
  assert.equal(manifest.scope, "/");
  assert.ok(manifest.start_url.startsWith("/"));
  assert.ok(manifest.icons.some((icon) => icon.sizes === "192x192" && icon.type === "image/png"));
  assert.ok(manifest.icons.some((icon) => icon.sizes === "512x512" && icon.purpose.includes("maskable")));

  await access("public/assets/pwa/icon-192.png");
  await access("public/assets/pwa/icon-512.png");
  await access("public/assets/pwa/apple-touch-icon.png");
});

test("service worker is generated by the build and bypasses the API", async () => {
  const config = await readFile("vite.config.js", "utf8");

  assert.match(config, /VitePWA/);
  assert.match(config, /navigateFallbackDenylist: \[\/\^\\\/api\\\/\/\]/);
  assert.match(config, /NetworkOnly/);
});
